version: 0.0
os: windows
files:
  - source: /
    destination: C:\inetpub\wwwroot  # This is where IIS hosts web applications in default configuration.

hooks:
  BeforeInstall:
    - location: scripts/stop_iis.ps1
      timeout: 300
      runas: Administrator

  AfterInstall:
    - location: scripts/install_dependencies.ps1
      timeout: 600
      runas: Administrator

  ApplicationStart:
    - location: scripts/start_iis.ps1
      timeout: 300
      runas: Administrator

  ValidateService:
    - location: scripts/validate_service.ps1
      timeout: 300
      runas: Administrator
