version: 0.0
os: windows

files:
  - source: /
    destination: C:\inetpub\wwwroot\SimpleBackend

hooks:
  BeforeInstall:
    - location: scripts/stop_service.ps1
      timeout: 300
      runas: Administrator

  AfterInstall:
    - location: scripts/start_service.ps1
      timeout: 300
      runas: Administrator
