version: 0.2

phases:
  install:
    commands:
      - echo "Installing zip utility..."
      - choco install zip -y  # Install zip utility using Chocolatey
  build:
    commands:
      - echo "Building the code..."
      - $commitHash = "$env:CODEBUILD_RESOLVED_SOURCE_VERSION"  # Get the commit hash
      - $sanitizedCommitHash = $commitHash -replace '[^a-zA-Z0-9]', '_'  # Sanitize the commit hash
      - echo "Using commit hash: $sanitizedCommitHash"
      - Compress-Archive -Path * -DestinationPath "${sanitizedCommitHash}.zip"  # Zip the entire source code directory
artifacts:
  files:
    - "${sanitizedCommitHash}.zip"  # Specify the zip file named after the sanitized commit hash
  discard-paths: yes  # Discard paths to store the zip directly in S3
