version: 0.2

phases:
  install:
    commands:
      - echo "Starting the build process..."
  
  pre_build:
    commands:
      - echo "Fetching source code..."

  build:
    commands:
      - echo "Zipping the source code..."
      # Create the output directory if it doesn't exist
      - mkdir -p output
      # Zip the source code, excluding the output directory
      - powershell Compress-Archive -Path * -DestinationPath output/source-code.zip

  post_build:
    commands:
      - echo "Build process complete. Ready to upload artifacts."

artifacts:
  files:
    - '**/*'  # Include all files in the output directory
  base-directory: output
  discard-paths: no
