version: 0.2

phases:
  install:
    commands:
      - echo "Starting the build process..."
      - echo "Simulating installation process..."
      - sleep 120  # Simulate installation time

  pre_build:
    commands:
      - echo "Simulating pre-build process..."
      - sleep 60  # Simulate pre-build time

  build:
    commands:
      - echo "Simulating build process..."
      - sleep 120  # Simulate build time

  post_build:
    commands:
      - echo "Zipping the source code..."
      # Zip the source code (all files in the current directory) into the output directory
      - mkdir -p output
      - powershell Compress-Archive -Path * -DestinationPath output/source-code.zip

artifacts:
  files:
    - output/**/*  # Include all files in the output directory

  base-directory: output  # Base directory for artifacts
  discard-paths: no       # Keep the directory structure

  destination:
    bucket: fujitech-codepipeline-artifacts-bucket-8586  # Replace with your S3 bucket name
    path: codebuild/artifacts         # Customize the path within the S3 bucket
