version: 0.2

env:
  variables:
    S3_BUCKET: "fujitech-codepipeline-artifacts-bucket-8586"
    S3_PREFIX: "codebuild/artifacts"

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo "Starting the process..."
      - aws --version
  
  pre_build:
    commands:
      - echo "Preparing to zip source code..."

  build:
    commands:
      - echo "Zipping the source code..."
      - mkdir -p $CODEBUILD_SRC_DIR/output
      - powershell Compress-Archive -Path * -Exclude output -DestinationPath $CODEBUILD_SRC_DIR/output/source-code.zip

  post_build:
    commands:
      - echo "Zipping complete. Uploading to S3..."
      - aws s3 cp $CODEBUILD_SRC_DIR/output/source-code.zip s3://$S3_BUCKET/$S3_PREFIX/source-code-$(date +%Y-%m-%d-%H-%M-%S).zip

artifacts:
  files:
    - '**/*'
  base-directory: output
  name: source-code-$(date +%Y-%m-%d-%H-%M-%S).zip
  discard-paths: no