version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo "Starting the build process..."
      - dotnet --version
  
  pre_build:
    commands:
      - echo "Fetching source code..."

  build:
    commands:
      - echo "Building the application..."
      - dotnet build --configuration Release
      - echo "Zipping the build output..."
      - mkdir -p $CODEBUILD_SRC_DIR/output
      - powershell Compress-Archive -Path $CODEBUILD_SRC_DIR/bin/Release/* -DestinationPath $CODEBUILD_SRC_DIR/output/build-output.zip

  post_build:
    commands:
      - echo "Build process complete. Ready to upload artifacts."

artifacts:
  files:
    - '**/*'
  base-directory: output
  name: build-output-$(date +%Y-%m-%d-%H-%M-%S).zip
  discard-paths: no