version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo "Starting the build process..."

  pre_build:
    commands:
      - echo "Preparing to zip source code..."
      - $env:GIT_COMMIT_HASH = $(git rev-parse --short HEAD)
      - echo "Commit hash: $env:GIT_COMMIT_HASH"

  build:
    commands:
      - echo "Zipping the source code..."
      - Compress-Archive -Path * -DestinationPath "$env:GIT_COMMIT_HASH.zip" -Force

  post_build:
    commands:
      - echo "Build complete. Artifact ready for storage."

artifacts:
  files:
    - $env:GIT_COMMIT_HASH.zip
  name: $env:GIT_COMMIT_HASH.zip
  discard-paths: yes