version: 0.2

phases:
  install:
    commands:
      - echo "Installing zip utility..."
      - choco install zip -y  # Install zip utility using Chocolatey
  build:
    commands:
      - echo "Building the code..."
      - $commitHash = "$env:CODEBUILD_RESOLVED_SOURCE_VERSION"  # Get the commit hash
      - Compress-Archive -Path * -DestinationPath "${commitHash}.zip"  # Zip the entire source code directory
artifacts:
  files:
    - "${env:CODEBUILD_RESOLVED_SOURCE_VERSION}.zip"  # Specify the zip file named after the commit hash
  discard-paths: yes  # Discard paths to store the zip directly in S3
