version: 0.2

phases:
  install:
    commands:
      - echo "Starting the build process..."
  
  pre_build:
    commands:
      - echo "Fetching source code..."

  build:
    commands:
      - echo "Zipping the source code..."
      # Create the output directory if it doesn't exist
      - mkdir -p output
      # Zip the source code, excluding the output directory
      - powershell Compress-Archive -Path * -DestinationPath output/source-code.zip

  post_build:
    commands:
      - echo "Build process complete. Ready to upload artifacts."

artifacts:
  files:
    - 'source-code.zip'  # Upload only the zip file

  base-directory: output  # Directory where the zip is created
  discard-paths: no       # Retain the directory structure

  # Artifact storage location within S3
  # Note: Remove this section if the bucket is managed by the pipeline (optional to add)
  destination: fujitech-codepipeline-artifacts-bucket-8586/codebuild/artifacts
